[package]
name = "dirty-entropy-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paspio = "1.0.0"
zxcvbn = "2.2.1"
